services:
  frontend:
    build:
      context: ./client
    ports:
      - '${WEB_PORT}:3000'
    volumes:
      - ./client:/app/client:cached
    networks:
      - app_network

  backend:
    build:
      context: ./server
    ports:
      - '${API_PORT}:3000'
      - 40000-40020:40000-40020/udp
    links:
      - db
      - redis
    volumes:
      - ./server:/app/server:cached
      - node_modules:/app/server/node_modules
    networks:
      - app_network

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links: 
      - db
    networks:
      - app_network

  redis:
    image: redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  node_modules:
