services:
  backend:
    build:
      context: ./server
    ports:
      - '${API_PORT}:3000'
      - 40000-40020:40000-40020/udp
    links:
      - db
      - redis
    volumes:
      - ./server:/app:cached
    networks:
      - app_network

  frontend:
    build:
      context: ./client
    ports:
      - '${WEB_PORT}:3000'
      - 24678:24678
    volumes:
      - ./client:/app:cached
    networks:
      - app_network

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - db
    networks:
      - app_network

  redis:
    image: redis
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
